const DEFAULT_ORIGIN="https://educationboardresults.gov.bd";
export function origin(env:any){return (env.UPSTREAM_ORIGIN||DEFAULT_ORIGIN).replace(/\/+$/,'');}
export function corsHeaders(){return {"Access-Control-Allow-Origin":"https://www.mybdresults24.com","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type","Vary":"Origin"};}
export function json(data:any,request:Request,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","Pragma":"no-cache",...corsHeaders()}});}
export function bad(request:Request,message:string,status=400){return json({ok:false,error:message},request,status);}
export function getSetCookies(h:Headers){const x=h as any;if(typeof x.getSetCookie==='function')return x.getSetCookie();const v=h.get('set-cookie');return v?[v]:[];}
export function cookieHeader(a:string[]){return a.map(x=>x.split(';')[0]).filter(Boolean).join('; ');}
export function extractCookie(a:string[],name:string){for(const x of a){const m=x.match(new RegExp(name+'=([^;]+)'));if(m)return m[1];}return '';}
function b64(b:ArrayBuffer|Uint8Array){const a=b instanceof Uint8Array?b:new Uint8Array(b);let s='';for(const x of a)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function ub64(s:string){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const r=atob(s);return Uint8Array.from(r,c=>c.charCodeAt(0));}
export async function signToken(payload:any,secret:string){const body=b64(new TextEncoder().encode(JSON.stringify(payload)));const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(body));return body+'.'+b64(sig);}
export async function verifyToken(token:string,secret:string){const [body,sig]=token.split('.');if(!body||!sig)throw Error('Invalid session token');const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify']);if(!await crypto.subtle.verify('HMAC',k,ub64(sig),new TextEncoder().encode(body)))throw Error('Invalid session token');const p=JSON.parse(new TextDecoder().decode(ub64(body)));if(!p.exp||Date.now()>p.exp)throw Error('Session expired');return p;}
export function abs(base:string,v:string){try{return new URL(v,base).toString()}catch{return new URL('/v2/captcha',base).toString()}}
export function captchaSrc(html:string){for(const m of html.matchAll(/<img\b[^>]*>/gi)){const t=m[0],s=t.match(/\bsrc\s*=\s*["']([^"']+)["']/i)?.[1];if(s&&/captcha|capcha|security|robot/i.test(t+s))return s;}return '';}
export function text(html:string){return html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?>/gi,'\n').replace(/<\/(td|th|tr|p|div|li|h[1-6])>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/\s+/g,' ').trim();}
export function parseResultHtml(html:string,roll:string,reg:string){const t=text(html);const pick=(ls:string[])=>{for(const l of ls){const m=t.match(new RegExp(l+'\\s*[:\\-]?\\s*([^\\n|]{1,120})','i'));if(m)return m[1].trim();}return '';};const student:any={name:pick(['Name of Student','Student Name','Name']),father:pick(["Father's Name",'Father Name','Fathers Name']),mother:pick(["Mother's Name",'Mother Name','Mothers Name']),institute:pick(['Name of Institution','Institution Name','Institute Name']),board:pick(['Board','Name of Board']),exam:pick(['Examination','Exam']),year:pick(['Year','Passing Year']),roll:pick(['Roll','Roll Number'])||roll,registration:pick(['Registration','Registration Number','Reg. No'])||reg,group:pick(['Group']),result:pick(['Result','Result Status']),gpa:pick(['GPA','Grade Point Average'])};const subjects:any[]=[];for(const r of html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){const c=[...r[1].matchAll(/<(?:td|th)\b[^>]*>([\s\S]*?)<\/(?:td|th)>/gi)].map(x=>text(x[1]));if(c.length>=3&&!/(subject|code|grade|letter|point)/i.test(c.join(' | '))&&(c.some(x=>/^[A-F][+]?$/i.test(x))||/^\d{2,4}$/.test(c[0])))subjects.push({code:c[0]||'',subject:c[1]||'',grade:c[2]||c[3]||''});}return {student,subjects,source:'educationboardresults.gov.bd'};}
